Add CI environment variable and installation of modules

diff --git a/ui/Dockerfile b/ui/Dockerfile
--- a/ui/Dockerfile
+++ b/ui/Dockerfile
@@ -28,6 +28,14 @@ COPY . .
 # Learn more here: https://nextjs.org/telemetry
 # Uncomment the following line in case you want to disable telemetry during the build.
 # ENV NEXT_TELEMETRY_DISABLED=1
+ENV CI=true
+
+RUN \
+  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 RUN \
   if [ -f yarn.lock ]; then yarn run build; \
